### ISSUE TITLE
Renard Out sketch overwrites data array

### ISSUE THREAD

**Issue by dkulp** [komby/RFShowControl#32]
The code in the Rendard Out sketch looks like:

```
  for (int i = 0; i < strip.GetElementCount(); i++)
  {
    strip.SetElementColor(i, strip.Color(0, 0, 0));
  }
```
The GetElementCount is returning "64" as I have HARDCODED_NUM_CHANNELS set to 64.   However, the SetElementColor is assuming 3 bytes per element and is then overwriting the data array and then causing memory corruption.   For me, this is resulting in a continuous reboot.

**Comment by komby** [comment]
Ill take a look tonight.

**Comment by dkulp** [comment]
Actually, I think I found the real problem:

```
-  strip.Begin(radio.GetControllerDataBase(logicalControllerNumber), radio.GetNumberOfChannels(logicalControllerNumber++));
+ strip.Begin(radio.GetControllerDataBase(logicalControllerNumber), radio.GetNumberOfChannels(logicalControllerNumber));
```
For some reason, the 1.6.5 (and 1.6.6 BTW) compiler is evaluating the second param first so the logicalControllerNumber is being incremented before calling into GetControllerDataBase.   In GetControllerDataBase, I'm getting the value as 1 which doesn't make sense.   Removing the increment fixes a bunch of my issues.  (that said, the pixel init code shouldn't be needed as you alloc with calloc)

**Comment by dkulp** [comment]
That got me further, but I still couldn't get the sketch to work with my Kombee with a MiniRen8.   For some reason, the printf and printf_P calls in RFShowControl.cpp would just block if DEBUG wasn't defined (so printf.h was loaded and initialized).   I added 
```
#define printf_P(...)
#define printf(...)
```
to the top of RFShowControl.cpp and now I am getting data out of the Renard and my lights blink and flash correctly.

**Comment by komby** [comment]
looks like the #include "printf.h"   was commented out in the sketch file.   If its changed to #include <printf.h> will it work without the extra defines?

**Comment by dkulp** [comment]
Hmm... cannot reproduce that issue now.  I'll try again tomorrow.  I had all kinds of Serial.println(..) things scattered throughout the code to try and figure out the hangs related to the logicalControllerNumber issue above.  They may have caused some other issues.  In anycase, the remove of the increment above helped a TON.  (this may be the same as issue #22 BTW)

**Comment by komby** [comment]
Updated tonight with a fix that should take care of this issue.

**Comment by dkulp** [comment]
Did some more testing... I grabbed the latest code from github and I'm still getting a complete hang in the setup() method in the call to GetControllerDataBase.    It looks like 1.6.6 on the Mac isn't initializing stdout correctly.   I ended up doing:
'''

#ifndef DEBUG
int null_out_function(char c, FILE *stream) {return 0;}
#endif
void setup(void)
{
#ifndef DEBUG
fdevopen( &null_out_function, 0 );
#endif
'''
to make sure stdout is sent nowhere.   Once I did that, things look OK.

**Comment by komby** [comment]
I believe this is fixed in the current release
