### ISSUE TITLE
RF_Out_E131_IN missing include path

### ISSUE THREAD

**Issue by gothambeat** [komby/RFShowControl#33]
The ../../Ethernet/src/utility/util.h is missing.  The directory structure does not exist anymore and the sketches can't compile

**Comment by komby** [comment]
What platform are you compiling on

**Comment by gothambeat** [comment]
Windows 10

**Comment by komby** [comment]
Starting with https://github.com/komby/RFShowControl/releases/tag/4.0.1 we are supporting the newest version but it "should" support both.

**Comment by komby** [comment]
Closed in current release
